;(function(global,factory){"use strict";if(typeof module==="object"&&typeof module.exports==="object"){module.exports=global.document?factory(global,true):function(w){if(!w.document){throw new Error("Page requires a window with a document");}
return factory(w);};}else{factory(global);}})(typeof window!=="undefined"?window:this,function(window,noGlobal){function Page(options){this.el=options.el;this.nums=options.nums;this.counts=options.counts||10;this.parentNode=document.querySelector(this.el);this.defaultPage=options.defaultPage||1;this.last=this.nums%this.counts;this.pages=parseInt(this.nums/this.counts);this.showHeadFoot=!!options.showHeadFoot;this.head=options.head||'首页';this.foot=options.foot||'尾页';this.prev='«';this.next='»';this.headfoot=[];if(this.last!=0){this.pages++;}
this.div=options.div||'div';this.domList=[];this.showDomList=[];var that=this;function noop(){if(options.clickEvent&&typeof options.clickEvent=='function'){options.clickEvent(that.currect);}}
this.clickEvent=noop;this.init();}
Page.prototype={init:function(){this.createDom();this.showDom();this.watcherCurrect();this.addDom();this.reanderHeadFoot();},reanderHeadFoot:function(){if(!this.showHeadFoot){return;}
var div=this.div;var head=document.createElement(div);var foot=document.createElement(div);head.innerHTML=this.head;head.classList.add('item');head.classList.add('head');foot.innerHTML=this.foot;foot.classList.add('item');foot.classList.add('foot');this.headfoot.push(head);this.headfoot.push(foot);this.parentNode.insertBefore(head,this.parentNode.firstChild);this.parentNode.appendChild(foot);this.addEventHeadFoot();},addEventHeadFoot:function(){var that=this;this.headfoot[0].addEventListener('click',function(){if(that.currect!=1){that.currect=1;}});this.headfoot[1].addEventListener('click',function(){if(that.currect!=that.pages){that.currect=that.pages;}});},createDom:function(){var div=this.div;var domList=this.domList;var prev=document.createElement(div);var next=document.createElement(div);prev.innerHTML=this.prev;prev.classList.add('item');next.innerHTML=this.next;next.classList.add('item');domList[0]=prev;var pages=this.pages;for(var i=0;i<pages;i++){var item=document.createElement(div);item.classList.add('item');item.innerHTML=i+1;domList[i+1]=item;}
domList.push(next);return domList;},showDom:function(){var domList=this.domList;var len=domList.length;var list=this.showDomList;var defaultPage=this.defaultPage;if(len<=12){for(var i=0;i<len;i++){list[i]=domList[i];}}else{var offset=defaultPage-6<0?0:defaultPage-6;var cha=this.pages-defaultPage;if(cha<5){offset=this.pages-10;}
list[0]=domList[0];for(var i=1;i<11;i++){list[i]=domList[i+offset];}
list[i]=domList[len-1];}
return list;},addDom:function(){this.parentNode.classList.add('page-elem-field');this.addAndRemoveClass();this.addEvent();var fgDom=document.createDocumentFragment();var showDomList=this.showDomList;var len=showDomList.length;for(var i=0;i<len;i++){fgDom.appendChild(showDomList[i]);}
this.parentNode.appendChild(fgDom);},addEvent:function(){var domList=this.domList;var len=domList.length;for(var i=0;i<len;i++){domList[i].addEventListener('click',this.jump.bind(domList[i],this));}},jump:function jump(p){var thispage=this.innerHTML;if((thispage==p.prev&&p.currect==1)||(thispage==p.next&&p.currect==p.pages)||(thispage==p.currect)){return;}
if(thispage==p.prev&&p.currect>1){p.currect--;}else if(thispage==p.next&&p.currect<p.pages){p.currect++;}else if(thispage!=p.prev&&thispage!=p.next){p.currect=Number(thispage);}},addAndRemoveClass:function(){var domList=this.domList;if(this.currect===1){domList[0].classList.add('item-disable');}else if(this.currect===this.pages){domList[domList.length-1].classList.add('item-disable');}
domList[this.currect].classList.add('active');},watcherCurrect:function(){var val=this.defaultPage;var domList=this.domList;var showDomList=this.showDomList;var oneDomNumber=Number(showDomList[1].innerHTML);Object.defineProperty(this,'currect',{enumerable:true,configrable:false,set:function(v){domList[val].classList.remove('active');val=v;var cha=val-oneDomNumber;var moves=0;if(cha>5){moves=cha-5;var showlastnum=Number(showDomList[showDomList.length-2].innerHTML);var afters=this.pages-showlastnum;if(afters>0&&moves>0){var howmany=Math.min(afters,moves);for(var i=0;i<howmany;i++){showDomList.splice(showDomList.length-1,0,domList[showlastnum+i+1]);this.parentNode.insertBefore(domList[showlastnum+i+1],showDomList[showDomList.length-1]);this.parentNode.removeChild(showDomList[i+1]);}
showDomList.splice(1,howmany);}
oneDomNumber=Number(showDomList[1].innerHTML);}
if(cha<=5&&oneDomNumber!=1){var showfirstnum=Number(showDomList[1].innerHTML);if(val<=5){moves=showfirstnum-1;}else{moves=5-cha;}
var howmany=moves;for(var i=0;i<howmany;i++){this.parentNode.insertBefore(domList[showfirstnum-i-1],showDomList[1]);this.parentNode.removeChild(showDomList[showDomList.length-2-i]);showDomList.splice(1,0,domList[showfirstnum-i-1]);}
showDomList.splice(showDomList.length-1-howmany,howmany);oneDomNumber=Number(showDomList[1].innerHTML);}
domList[val].classList.add('active');domList[0].classList.remove('item-disable');domList[domList.length-1].classList.remove('item-disable');if(this.showHeadFoot){this.headfoot[0].classList.remove('item-disable');this.headfoot[1].classList.remove('item-disable');}
if(val==1){domList[0].classList.add('item-disable');if(this.showHeadFoot){this.headfoot[0].classList.add('item-disable');}}else if(val==this.pages){domList[domList.length-1].classList.add('item-disable');if(this.showHeadFoot){this.headfoot[1].classList.add('item-disable');}}
this.clickEvent(val);},get:function(){return val;}})}}
Page.prototype.constructor=Page;if(typeof noGlobal==="undefined"){window.Page=Page;}
return Page;})